python codes/mlp/main.py --is_train True --data_dir cifar-10_data --num_epochs 50 --batch_size 128 --learning_rate 1e-3 --drop_rate 0.0
python codes/mlp/main.py --is_train True --data_dir cifar-10_data --num_epochs 50 --batch_size 128 --learning_rate 1e-3 --drop_rate 0.1
python codes/mlp/main.py --is_train True --data_dir cifar-10_data --num_epochs 50 --batch_size 128 --learning_rate 1e-3 --drop_rate 0.2
python codes/mlp/main.py --is_train True --data_dir cifar-10_data --num_epochs 50 --batch_size 128 --learning_rate 1e-3 --drop_rate 0.3
python codes/mlp/main.py --is_train True --data_dir cifar-10_data --num_epochs 50 --batch_size 128 --learning_rate 1e-3 --drop_rate 0.4
python codes/mlp/main.py --is_train True --data_dir cifar-10_data --num_epochs 50 --batch_size 128 --learning_rate 1e-3 --drop_rate 0.5
python codes/mlp/main.py --is_train True --data_dir cifar-10_data --num_epochs 50 --batch_size 128 --learning_rate 1e-3 --drop_rate 0.6
python codes/mlp/main.py --is_train True --data_dir cifar-10_data --num_epochs 50 --batch_size 128 --learning_rate 1e-1 --drop_rate 0.5
python codes/mlp/main.py --is_train True --data_dir cifar-10_data --num_epochs 50 --batch_size 128 --learning_rate 5e-2 --drop_rate 0.5
python codes/mlp/main.py --is_train True --data_dir cifar-10_data --num_epochs 50 --batch_size 128 --learning_rate 1e-2 --drop_rate 0.5
python codes/mlp/main.py --is_train True --data_dir cifar-10_data --num_epochs 50 --batch_size 128 --learning_rate 5e-3 --drop_rate 0.5
python codes/mlp/main.py --is_train True --data_dir cifar-10_data --num_epochs 50 --batch_size 128 --learning_rate 5e-4 --drop_rate 0.5
python codes/mlp/main.py --is_train True --data_dir cifar-10_data --num_epochs 50 --batch_size 128 --learning_rate 1e-4 --drop_rate 0.5
python codes/mlp/main.py --is_train True --data_dir cifar-10_data --num_epochs 50 --batch_size 32 --learning_rate 1e-3 --drop_rate 0.5
python codes/mlp/main.py --is_train True --data_dir cifar-10_data --num_epochs 50 --batch_size 64 --learning_rate 1e-3 --drop_rate 0.5
python codes/mlp/main.py --is_train True --data_dir cifar-10_data --num_epochs 50 --batch_size 256 --learning_rate 1e-3 --drop_rate 0.5